<?php

namespace TahwissaBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function hasParticipated($user,$event){
        $qb= $this->createQueryBuilder("p");
        $qb->where("p.participant=:user")
            ->andWhere("p.evenement=:evenement")
            ->setParameter("user",$user)
            ->setParameter("evenement",$event);
        $res= $qb->getQuery()->getResult();
        if (sizeof($res)==0){
            return false;
        }
        else
            return true;
    }

    public function checherParticipant($id){
        $qb = $this->createQueryBuilder('w');
        $qb->where("w.participant = :participer")
            ->setParameters(array("participer"=>$id));
        return $qb->getQuery()->getResult();
    }

}
