<?php

namespace TahwissaBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUserAndEvent($user,$event){
        $qb= $this->createQueryBuilder("r");
        $qb->where("r.event=:event")
            ->andWhere("r.user=:user")
            ->setParameter("event",$event)
            ->setParameter("user",$user);
        $res= $qb->getQuery()->getResult();
        if (sizeof($res)==0){
            return null;
        }
        else
            return $res[0];
    }
}
